  ---
title: "Notes on references"
output:
  pdf_document: default
  html_document: default
bibliography: references.bibtex
---

```{r, echo = FALSE}
link_pdf <- function(key) {
  path <- list.files("pdfs", pattern = key, recursive = TRUE, full.names = TRUE)
  if (length(path) > 1) {
    stop("More than one PDF matches the key!")
  }
  paste0("## @", key, "\n\n[PDF](", path, ")")
}
```

## @bokulich2014microbial

* Grape variety plays a significant role in shaping microbial community patterns across all regions and vintages
* As the most dominant and discriminant taxa between regions and varieties have well-characterized impacts on grape and wine qualities, these differences may help explain regional patterns in wine chemicosensory properties 

## @sapkota2015host

*  The effects of cereal host genotype, fungicide treatment and location on fungal communities were explored
* Most fungal taxa were found to be cosmopolitan, as they were found in all cereal species, and, in general, only pathogens were found to be host specific
* Overall, samples were dominated by a few fungal species across all crops
* In general, filamentous fungi are considered to be transient inhabitants, whereas yeasts appear to be more permanent colonizers within the phyllosphere
* Crop genotype had the strongest effect on fungal community strucutre
* Surprisingly, only a few OTUs responded significantly to fungicide treatment, and these did not include some of the organisms that are normally targeted in fungicide applications (such as Z. tritici and B. graminis).


## @sapkota2017spatiotemporal

* Studied the effects of location, time, leaf age, and cultivar on the wheat fungal microbiome using ITS1 metabarcoding
* Found location to have the largest influence on fungal community structure in wheat, followed by leaf position, and cultivar
* Found that cultivar was most important in explaining variation in older leaves whereas location better explained the variation in younger leaves
* Network analysis revealed negative co-existence between Zymoseptoria tritici and various
yeasts 
* Found a correlation between Zymoseptoria tritici infection and read proportion up to 30% infection 


## @edgar2017accuracy

* Evaluated the accuracy of diversity metrics when using open/close-reference OTU calling with QIIME.
* Weighted UniFrac is much more tolerant of sequencing error than Jaccard
* The recommended protocol/settings of QIIME lead to an overestimates of diversity
* Different parts of 16S from the same sequence are often assigned to different taxa 


## @james2002infection

* Inoculated rice with Herbaspirillum seropedicae and obseverd infection with microscopy and nutrient analysis.
* Bacteria enter through cracks at lateral root junctions
* Inhabit arenchyma and swell open spaces. Slight host repsonse
* N fixation is variable and highy dependendt on plant genotpye


## @de1996biological

* Applied a selection of azospirillum strains to a selection of maize cultivars and measured 15N accumulation, biomass, and N. 
* Different culivars/strain combinations had difference responses
* In 2 of the 4 cultivars, the addition of some strains of azospirillum was equalvalent to 100 kg N / ha fertilizer.

## @de1996maize

* A two-year study of the effects of azospirillum innoculation on differnt cultivars of maize.
* Found consistent veriation in grain production, nitrase activity, and N levels that differed between cultivars.
* Azospirillum species have been studied as innoculatants of cereal crops.

## @wu1995molecular

* Used F2 crosses of two rice cultivars, 15N labled soil, and RFLP to determine if N-fixation was determined gentically.
* Most bacteria in the rhizosphere of rice are N-fixing. (Watanabe 1981)
* One cultivar fixed 23% more N than the other. 
* 16% of the variability of N-fixation in F2 plants was attributed to 4 QTLs.


## @james2000nitrogen

* N2^15 is used to test for nitrogen fixation, but as of 2000, studies have been too long to differentiate between free living N fixers decomposing and symbionts.



`r link_pdf("singer2016high")`

Surveyed oomycete diversity in acidic peat bogs in the Jura Mountains of Switzerland and France using Illumina HiSeq sequencing of V9 SSU using universal primers [@amaral2009method].
The MoBio soil kit was used to extract DNA from 65 samples of Sphagenum moss from differnt micohabitats. 3% of the total sequencing was oomycetes and an average of about 16 phylotypes per sample were found constituting a total of 34, although only 3 phylotypes matched their refernece sequence 100%.
There was no significant difference between the 5 sites sampled, but there was a difference between microhabitates, particulary between pools and the more terrestrial ones.
Most of the oomycetes they found were assinged to uncharacterized basal clades. They found some realted to pathogens of animals and plants, but its hard to infer ecosystem function from a 180bp barcode.  


## @lara2011highly 

Used cloneing and sequencing to explore the diversity of protists in sphagenum-dominated bogs and poor fens in the Jura Mountains.
5 water samples yeilded 1070 sequences and 132 phylotypes.
Two SSU primer pairs were used and had different results: 1F/1498R and 82F/1498R.
500ml of water was filtered through 50uM and 0.2uM and DNA was extracted from the 0.2uM filter.
Used phylogenetic methods to analyze community relationships and found evidence for new eukaryotic clade.
Chrysophyaceae was common, particulary in the winter. 


## @rodriguez2015role 

Nitrogen and phosphorous are typically limiting and can be made accessible by nitrogen-fixing bacteria and arbuscular mycorrhizal fungi (AMF) respectively. 
Nitrogen-fixing bacteria are being actively used, but the use of AMF is hampered by insufficient research on yield effects and the need of plants for large-scale culturing of AMF.
Research comparing inoculated vs sterile soil demonstrate a large benefit of AMF, but since AMF are associated with all crop plants naturally, this is rather artificial, and effects of AMF inoculation of plants with existing AMF communities are less consistent.
Only cassava has shown a significant and consistent yield increase of ~20%.
More research on how AMF inoculations affect natural communities is needed. 
There is little evidence on how specific AMF are to host and environment or how quickly they can adapt.
Different isolates of the same AMF species can have drastically different effects of crop yield.
There is also evidence to a lesser degree that host genotype has a significant effect as well. 
More research is needed on the persistence/spread of introduced AMF populations in agriculture systems as well as spread of introduced alleles to native populations. 


## @links2014simultaneous

Many OTUs were shared between brassica and triticum seeds and there was no detectable difference in richness or evenesss. This semms odd considering one is monocot and one a dicot. Perhaps this is due to them being commonly grown in a crop rotation.

?Hierarchical clustering

An antagonistic reaction was found between pantoea agglomerans, a bacterial biocontrol of fireblight, and an Alternaria species, a ascomycete plant pathogen.

chaperonin 60 (cpn60) also called heat schock protein 60 (hsp60) was used as the barcode since it is present in both bcateria and fungi.  


Hashidoko, 2005; Critzer & Doyle, 2010

Hallmann et al., 1997

Lucero et al., 2011

Hallmann et al., 1997;
Lucero et al., 2011

Johnston-Monje
& Raizada, 2011


## @mengual2014microbial

* Rhizobacteria are known to increase root surface area, nitrogen fixation, and phosphate and potassium availability.
* Found increased lavender growth in response to sugar beet compost and various bacillus species. 
* Addressing the issue of revegitating degraded mediterranian soils.

## @turner2013plant

* Has lots of good things to say about the microbiome
* 5-20% total photosynthesis production goes to rhizobiome
* archea in agriculture contribute to ammonia oxidation and methanogensis
* rhizobium forms nodules on legumes
* azotobacter is a free living N-fixer
* actinomycetes tend to produce antimicrobials 
* bcateria in the phylosphere might have photosynthetic rhodopisins with non-overlappping spetra
* endophytes are mostly in the apoplast and dead cells
* there are more endophytes in lower roots than shoots, perhaps suggesting that they travel upwards.
* the microbiome can increase systemic resistance in plants
* Some bacteria like rhizobia and bacillus can produce plant hormones. 
* Rhizobia is a lifestyle, rhizobium is a genuss

## @taylor2017nitrogen

* In 7 plots in costa rican rainforests the DBH of nitrogen fixers correlated negativly with the biomass change of non-nitrogen fixers.

# References