---
title: "Things to read"
bibliography: "references.bib"
output: html_document
---


## To read

* @gansner2008efficient
* @boddey1995n2
* @sevilla1998contributions
* @sevilla2000genetic
* @bokulich2014microbial
* @reinhold2011living
* @bulgarelli2012revealing
* @lundberg2012defining
* @inceouglu2011comparative
* @teixeira2010bacterial
* @ji2013reliable
* @lott2015covenntree
* @singer2016high
* @wang2015orthovenn
* @harpole2016addition
* @cock2010sanger
* @nichols2016simera
* Evaluation of 16S rRNA Gene Primer Pairs for Monitoring Microbial Community Structures Showed High Reproducibility within and Low Comparability between Datasets Generated with Multiple Archaeal and Bacterial Primer Pairs
* @barrow2008symbiotic
* @fernandes2014unifying
* @white2009statistical
* @segata2011metagenomic
* @mandal2015analysis
* @lovell2015proportionality
* @friedman2012inferring
* @kurtz2015sparse
* @martin1998measures
* @kelly2015power
* @richardson2016evaluating

## Read again

* @weiss2016correlation
* @coleman2016plant
* @mengual2014microbial
* @james2000nitrogen

## References